# Generated by Django 3.1.5 on 2021-05-19 17:44

import author.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('picture', models.ImageField(default=None, null=True, upload_to=author.models.author_picture_file_name)),
            ],
        ),
    ]
