version: "3.0"
services:
  app:
    build:
      context: .
    expose:
      - 8000
    volumes:
      - ./app:/app
      - ./app/media/:/usr/share/nginx/html/media/
    command: >
      sh -c "python manage.py wait_for_database &&
             python manage.py migrate &&
             gunicorn app.wsgi:application  --bind 0.0.0.0:8000"
    depends_on:
      - db

  db:
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "challenge"
      POSTGRES_DB: "challenge"
  
  nginx:
    build: ./nginx
    volumes:
      - ./app/media/:/usr/share/nginx/html/media/
    ports:
      - 8080:80
    depends_on:
      - app