# Generated by Django 3.1.5 on 2021-05-20 20:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20210520_1733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='author_id',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='article',
            name='first_paragraph',
        ),
        migrations.AddField(
            model_name='article',
            name='firstParagraph',
            field=models.TextField(default=datetime.datetime(2021, 5, 20, 20, 23, 12, 33901, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
